config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'admin/words/import', to: 'admin/words#import'

  root 'dashboard#index'

  resources :tests, only: [:new, :create, :show, :update]
  post '/words' => 'words#index', constraints: { format: :json }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord

  validates :number, presence: true, uniqueness: true
  validates :number, numericality: { greater_than: 0 }, if: lambda { self.number.present? }

  has_many :words
end

app/models/question.rb
class Question < ApplicationRecord

  validates :user_answer, presence: true, on: :update

  belongs_to :test
  belongs_to :word
  delegate :content, to: :word, prefix: :word
  delegate :meaning, to: :word, prefix: :word

  def answers
    [answer_1, answer_2, answer_3, answer_4]
  end
end

app/models/test.rb
class Test < ApplicationRecord

  attr_accessor :high_priority, :lesson_numbers

  validates :total_questions, presence: true
  validates :correct_question_count, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :user
  has_many :questions

  accepts_nested_attributes_for :questions

  def create_questions(test_params)
    high_priority = test_params[:high_priority].to_i > 0
    lesson_numbers = test_params[:lesson_numbers].reject(&:empty?).map(&:to_i)
    if high_priority
      words = Word._lesson_ids(lesson_numbers)._correct_rate_asc.limit(total_questions)
    else
      words = Word._lesson_ids(lesson_numbers).random.limit(total_questions)
    end
    questions = words.shuffle.map do |word|
      question = QuestionService.new(word).question
      Question.new(word_id: question[:word_id],
        answer_1: question[:ans_1], answer_2: question[:ans_2],
        answer_3: question[:ans_3], answer_4: question[:ans_4]
      )
    end
    self.questions = questions
  end

  def test_number
    "#{created_at.strftime('%Y%m%d')}_#{id}"
  end

  def update_correct_question_count
    count = 0
    questions.includes(:word).each do |question|
      count += 1 if question.user_answer == question.word_meaning
    end
    self.update(correct_question_count: count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  enum role: %i(admin user)

  has_many :tests
end

app/models/word.rb
class Word < ApplicationRecord

  validates :content, :meaning, :romaji, presence: true

  belongs_to :lesson
  has_many :questions
  delegate :number, to: :lesson, prefix: :lesson

  scope :_ids, ->(ids) {
    where(id: ids)
  }

  scope :_not_ids, ->(ids) {
    where.not(id: ids)
  }

  scope :_lesson_ids, ->(lesson_ids) {
    where(lesson_id: lesson_ids)
  }

  scope :random, -> {
    order(Arel.sql(Settings.random_scope[ActiveRecord::Base.connection.instance_values["config"][:adapter]]))
  }

  scope :_correct_rate_asc, -> {
    order(correct_rate: :asc)
  }

  scope :_count_by_lesson, ->(lesson_ids) {
    where(lesson_id: lesson_ids).group(:lesson_id).count
  }

  def to_romaji
    content.romaji
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_user
  before_action :load_tests

  def load_user
    @user = User.first
  end

  def load_tests
    @tests = @user.tests
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :update]

  def show
    @test = Test.find_by(id: params[:id])
    return redirect_to root_path unless @test
    @questions = @test.questions.includes(:word)
  end

  def new
    set_lessons
    set_number_question_option
    @test = Test.new
  end

  def create
    test = Test.new(
      total_questions: test_params[:total_questions].to_i,
      user_id: User.first.id
    )
    ActiveRecord::Base.transaction do
      if test.save
        test.create_questions(test_params)
        redirect_to test
      end
    end
  end

  def update
    return redirect_to @test if @test.status
    @test.assign_attributes(submit_test_params)
    if @test.save && @test.update_correct_question_count
      redirect_to @test
    end
  end

  private

  def set_test
    @test = Test.find_by(id: params[:id])
    return redirect_to root_path unless @test
  end

  def set_lessons
    @lessons = Lesson.all
  end

  def set_number_question_option
    @number_question_option = (1..@lessons.size).map do |i|
      i*30
    end
  end

  def test_params
    params.require(:test).permit(:high_priority, :total_questions, lesson_numbers: [])
  end

  def submit_test_params
    params.require(:test).permit(questions_attributes: [:id, :user_answer]).merge(status: 1)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    lessons = params[:lessons]
    total_words = Word._count_by_lesson(lessons).values.sum
    step = (total_words.to_f / 7).ceil
    word_options = (10..total_words-10).step(step).map do |words|
      words
    end
    word_options << total_words
    render json: word_options
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper

  def user_ans(submited, right_ans, user_ans, current_ans)
    return if !submited || user_ans != current_ans
    if right_ans == user_ans
      'right-ans'
    else
      'wrong-ans'
    end
  end

  def right_ans(submited, right_ans, user_ans, current_ans)
    return unless submited
    'right-ans' if right_ans == current_ans
  end
end

app/views/admin/words/_import_form.html.erb
<%= link_to 'Import CSV', 'javascript:;', id: 'words-import-btn' %>

<%= form_for :word, url: admin_words_import_path, multipart: true, html: { class: 'hidden' } do |f| %>
  <%= f.file_field :file, id: 'upload-words-btn' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoJav</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/preloader' %>
    <div id="main-wrapper">
      <%= render 'shared/topbar' %>
      <%= render 'shared/left_sidebar' %>
      <div class="page-wrapper">
        <%= render 'shared/page_breadcrumb' %>
        <div class="container-fluid">
          <%= yield %>
        </div>
        <%= render 'shared/footer' %>
      </div>
    </div>
    <%= yield(:javascript) %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer text-center">
</footer>

app/views/shared/_left_sidebar.html.erb
<aside class='left-sidebar'>
  <div class='scroll-sidebar'>
    <nav class='sidebar-nav'>
      <ul id='sidebarnav'>
        <li>
          <div class='user-profile d-flex no-block dropdown mt-3'>
            <div class='user-pic'>
              <%= image_tag 'templates/default_avatar.jpg', class: 'rounded-circle', width: 40 %>
            </div>
            <div class='user-content hide-menu ml-2'>
              <%= link_to '#', id: 'user-profile', role: 'button', data: { toggle: 'dropdown' },
                aria: { haspopup: true, expanded: false } do %>
                <h5 class='mb-0 user-name font-medium'>Quyen Nguyen <i class='fa fa-angle-down'></i></h5>
                <span class='op-5 user-email'>quyenguyengoc911@gmail.com</span>
              <% end %>
              <div class='dropdown-menu dropdown-menu-right' aria-labelledby='user-profile'>
                <%= link_to 'javascript:;', class: 'dropdown-item' do %>
                  <i class='ti-user mr-1 ml-1'></i> My Profile</a>
                <% end %>
                <div class='dropdown-divider'></div>
                <%= link_to 'javascript:;', class: 'dropdown-item' do %>
                  <i class='fa fa-power-off mr-1 ml-1'></i> Logout
                <% end %>
              </div>
            </div>
          </div>
        </li>
        <li class='sidebar-item'>
          <%= link_to 'javascript:;', class: 'sidebar-link has-arrow waves-effect waves-dark', aria: { expanded: false } do %>
            <i class='mdi mdi-book'></i><span class='hide-menu'>Test </span>
          <% end %>
          <ul aria-expanded='false' class='collapse first-level'>
            <li class='sidebar-item'>
              <%= link_to new_test_path, class: 'sidebar-link' do %>
                <i class='mdi mdi-network-question'></i><span class='hide-menu'> New test</span>
              <% end %>
            </li>
            <% @tests.each do |test| %>
              <li class='sidebar-item'>
                <%= link_to test_path(test), class: "sidebar-link #{'not-submited-test' unless test.status}" do %>
                  <i class='mdi mdi-network-question'></i><span class='hide-menu'><%= test.test_number %></span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/shared/_page_breadcrumb.html.erb
<div class="page-breadcrumb">
  <div class="row">
    <div class="col-5 align-self-center">
      <h4 class="page-title">Dashboard</h4>
      <div class="d-flex align-items-center">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">Test</li>
            <li class="breadcrumb-item active" aria-current="page">New</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>

app/views/shared/_preloader.html.erb
<div class="preloader">
  <div class="lds-ripple">
    <div class="lds-pos"></div>
    <div class="lds-pos"></div>
  </div>
</div>

app/views/shared/_topbar.html.erb
<header class='topbar'>
  <nav class='navbar top-navbar navbar-expand-md navbar-dark'>
    <div class='navbar-header'>
      <%= link_to 'javascript:;', class: 'nav-toggler waves-effect waves-light d-block d-md-none' do %>
        <i class='ti-menu ti-close'></i>
      <% end %>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <b class='logo-icon'>
          <%= image_tag 'templates/logo-icon.png', class: 'dark-logo' %>
        </b>
        <span class='logo-text'>
          <%= image_tag 'templates/logo-text.png', class: 'dark-logo' %>
        </span>
      <% end %>
      <%= link_to 'javascript:;', class: 'topbartoggler d-block d-md-none waves-effect waves-light',
        aria: { controls: 'navbarSupportedContent', expanded: false , label: 'Toggle navigation' },
        data: { toggle: 'collapse', target: '#navbarSupportedContent' } do %>
        <i class='ti-more'></i>
      <% end %>
    </div>
    <div class='navbar-collapse collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav float-left mr-auto'>
        <li class='nav-item d-none d-md-block'>
          <%= link_to 'javascript:;', class: 'nav-link sidebartoggler waves-effect waves-light', data: { sidebartype: 'mini-sidebar' } do %>
            <i class='mdi mdi-menu font-24'></i>
          <% end %>
        </li>
      </ul>
      <ul class='navbar-nav float-right'>
        <li class='nav-item dropdown'>
          <%= link_to '#', class: 'nav-link dropdown-toggle', id: 'navbarDropdown2', role: 'button',
            data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: false } do %>
            <i class='flag-icon flag-icon-us'></i>
          <% end %>
          <div class='dropdown-menu dropdown-menu-right animated bounceInDown' aria-labelledby='navbarDropdown2'>
            <%= link_to '#', class: 'dropdown-item' do %>
              <i class='flag-icon flag-icon-us'></i> English
            <% end %>
            <%= link_to '#', class: 'dropdown-item' do %>
              <i class='flag-icon flag-icon-jp'></i> Japanese
            <% end %>
          </div>
        </li>
        <li class='nav-item dropdown'>
          <%= link_to '#', class: 'nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic',
            data: { toggle: 'dropdown' }, aria: { haspopup: true, expanded: false } do %>
            <%= image_tag 'templates/default_avatar.jpg', class: 'rounded-circle', width: 31 %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-right user-dd animated flipInY'>
            <span class='with-arrow'>
              <span class='bg-primary'></span>
            </span>
            <div class='d-flex no-block align-items-center p-15 bg-primary text-white mb-2'>
              <div class=''>
                <%= image_tag 'templates/default_avatar.jpg', class: 'img-circle', width: 60 %>
              </div>
              <div class='ml-2'>
                <h4 class='mb-0'>Quyen Nguyen</h4>
                <p class=' mb-0'>quyenguyengoc911@gmail.com</p>
              </div>
            </div>
            <%= link_to '#', class: 'dropdown-item' do %>
              <i class='ti-user mr-1 ml-1'></i> My Profile
            <% end %>
            <div class='dropdown-divider'></div>
            <%= link_to '#', class: 'dropdown-item' do %>
              <i class='fa fa-power-off mr-1 ml-1'></i> Logout
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>